"""Initial Migrations

Revision ID: 07995fa37e04
Revises: 
Create Date: 2019-09-22 15:32:09.163987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07995fa37e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
